version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Build the Spring Boot application
      - run: mvn compile

      # Run unit tests
      - run: mvn test

      # Run integration tests
      - run: mvn verify

  deploy:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Deploy your application (replace this with your deployment steps)
      - run: echo "Deploying..."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
